# Generated by Django 5.2.15 on 2026-06-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(db_index=True, max_length=1024)),
                ('path', models.CharField(blank=True, default='', max_length=1024)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('protocol', models.CharField(blank=True, default='', max_length=16)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, default='', max_length=128)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('bucket', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(blank=True, default='', max_length=32)),
                ('sftpgo_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['username', '-received_at'], name='api_receive_usernam_6d77a3_idx')],
            },
        ),
    ]
