# Generated by Django 5.2.15 on 2026-06-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedfile',
            name='state',
            field=models.CharField(choices=[('receiving', 'Réception (avant S3)'), ('stored', 'Enregistré dans S3'), ('failed', 'Échec')], db_index=True, default='receiving', max_length=16),
        ),
        migrations.AddField(
            model_name='receivedfile',
            name='stored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
