# Generated by Django 5.2.15 on 2026-06-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_receivedfile_state_receivedfile_stored_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedfile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivedfile',
            name='reconciled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='receivedfile',
            name='state',
            field=models.CharField(choices=[('receiving', 'Réception (avant S3)'), ('stored', 'Enregistré dans S3'), ('failed', 'Échec'), ('deleted', 'Supprimé via SFTP'), ('missing', 'Absent de S3 (drift réconciliation)')], db_index=True, default='receiving', max_length=16),
        ),
    ]
