# Generated by Django 5.2.15 on 2026-06-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_receivedfile_deleted_at_receivedfile_reconciled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedfile',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivedfile',
            name='state',
            field=models.CharField(choices=[('receiving', 'Réception (avant S3)'), ('stored', 'Enregistré dans S3'), ('failed', 'Échec'), ('deleted', 'Supprimé via SFTP'), ('missing', 'Absent de S3 (drift réconciliation)'), ('archived', 'Archivé (sorti du board Live)')], db_index=True, default='receiving', max_length=16),
        ),
    ]
