# Generated by Django 5.2.15 on 2026-06-15 16:16

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_receivedfile_archived_at_alter_receivedfile_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('revoked', 'Révoqué')], default='active', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(db_index=True, max_length=32)),
                ('control', models.CharField(max_length=64)),
                ('result', models.CharField(choices=[('passed', 'Réussi'), ('failed', 'Échoué')], max_length=16)),
                ('monitoring_class', models.CharField(choices=[('blocking', 'Bloquant'), ('warning_action', 'Avertissement (action requise)'), ('warning_noaction', 'Avertissement (sans action)'), ('reject', 'Rejet (archivé, non retraité)'), ('recycle', 'Recyclage (retraitable)'), ('push', 'Confirmation (poussé)')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=api.models.now_ms)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.receivedfile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['file', 'stage', '-created_at'], name='api_event_file_id_700e7a_idx'), models.Index(fields=['monitoring_class'], name='api_event_monitor_8f5add_idx')],
            },
        ),
    ]
