# Generated by Django 5.2.15 on 2026-06-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_partner_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedfile',
            name='control_class',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
