# Generated by Django 5.2.15 on 2026-06-16 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_receivedfile_control_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('resolved', 'Traité')], db_index=True, default='resolved', max_length=16)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage', to='api.receivedfile')),
            ],
        ),
        migrations.CreateModel(
            name='TriageAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=32)),
                ('control', models.CharField(max_length=64)),
                ('monitoring_class', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('resolved', 'Résolu')], db_index=True, default='open', max_length=16)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stage', 'control', 'monitoring_class', 'reason'), name='uniq_triage_cause')],
            },
        ),
    ]
