# Generated by Django 5.2.15 on 2026-06-19 09:33

import django.db.models.deletion
from django.db import migrations, models

DEFAULT_CODE = 'GIL'


def create_default_and_backfill(apps, schema_editor):
    """Crée le SubTenant par défaut (``GIL``) et rattache toutes les lignes
    existantes (antérieures au multi-tenant) à ce locataire. Idempotent."""
    SubTenant = apps.get_model('api', 'SubTenant')
    Partner = apps.get_model('api', 'Partner')
    ReceivedFile = apps.get_model('api', 'ReceivedFile')
    Event = apps.get_model('api', 'Event')
    default, _ = SubTenant.objects.get_or_create(
        code=DEFAULT_CODE, defaults={'name': 'GIL (locataire par défaut)'})
    Partner.objects.filter(sub_tenant__isnull=True).update(sub_tenant=default)
    ReceivedFile.objects.filter(sub_tenant__isnull=True).update(sub_tenant=default)
    Event.objects.filter(sub_tenant__isnull=True).update(sub_tenant=default)


def unset_default(apps, schema_editor):
    """Réversible : on dénoue les FK (re-nullables au reverse de AddField) puis on
    supprime le SubTenant par défaut s'il n'a plus de dépendance."""
    SubTenant = apps.get_model('api', 'SubTenant')
    Partner = apps.get_model('api', 'Partner')
    ReceivedFile = apps.get_model('api', 'ReceivedFile')
    Event = apps.get_model('api', 'Event')
    default = SubTenant.objects.filter(code=DEFAULT_CODE).first()
    if not default:
        return
    Partner.objects.filter(sub_tenant=default).update(sub_tenant=None)
    ReceivedFile.objects.filter(sub_tenant=default).update(sub_tenant=None)
    Event.objects.filter(sub_tenant=default).update(sub_tenant=None)
    default.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_purge_non_push_filetriage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='sub_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='api.subtenant'),
        ),
        migrations.AddField(
            model_name='partner',
            name='sub_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='api.subtenant'),
        ),
        migrations.AddField(
            model_name='receivedfile',
            name='sub_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='api.subtenant'),
        ),
        migrations.RunPython(create_default_and_backfill, unset_default),
    ]
