# Generated by Django 5.2.15 on 2026-06-19 09:34

import django.db.models.deletion
from django.db import migrations, models


def backfill_code_and_channels(apps, schema_editor):
    """``code = username`` (provisoire) + un canal SFTP par partenaire existant.

    Chaque compte d'aujourd'hui = un Partner identifié par son ``username`` SFTPGo.
    On le projette en ``Channel(kind='sftp', identifier=username)`` : c'est ce canal
    qui portera désormais la résolution (par ``identifier``). ``active`` reflète le
    statut du partenaire. Idempotent (get_or_create sur (kind, identifier))."""
    Partner = apps.get_model('api', 'Partner')
    Channel = apps.get_model('api', 'Channel')
    for p in Partner.objects.all():
        if not p.code:
            p.code = p.username
            p.save(update_fields=['code'])
        Channel.objects.get_or_create(
            kind='sftp', identifier=p.username,
            defaults={'partner': p, 'sub_tenant': p.sub_tenant,
                      'active': p.status == 'active'},
        )


def reverse_backfill(apps, schema_editor):
    """Réversible : suppression des canaux SFTP créés ; ``code`` repart nullable au
    reverse de l'AddField."""
    Channel = apps.get_model('api', 'Channel')
    Channel.objects.filter(kind='sftp').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_subtenant_and_nullable_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sftp', 'SFTP'), ('email', 'E-mail'), ('web', 'Web'), ('url', 'URL (réservé)')], db_index=True, max_length=16)),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('rule', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='api.partner')),
                ('sub_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='api.subtenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'identifier'), name='uniq_channel_kind_identifier')],
            },
        ),
        migrations.RunPython(backfill_code_and_channels, reverse_backfill),
    ]
