# Generated by Django 5.2.15 on 2026-06-19 09:35

import django.db.models.deletion
from django.db import migrations, models


def backfill_caches(apps, schema_editor):
    """Pose les caches ``channel``/``partner`` depuis le canal SFTP correspondant
    au ``username`` du fichier. Compte non mappé (pas de canal) → laisse NULL
    (discovery). Backfill par lots pour rester efficace sur ~600 lignes."""
    ReceivedFile = apps.get_model('api', 'ReceivedFile')
    Channel = apps.get_model('api', 'Channel')
    by_identifier = {
        c.identifier: c
        for c in Channel.objects.filter(kind='sftp').select_related('partner')
    }
    for rf in ReceivedFile.objects.filter(channel__isnull=True):
        chan = by_identifier.get(rf.username)
        if chan is None:
            continue
        rf.channel = chan
        rf.partner = chan.partner
        rf.save(update_fields=['channel', 'partner'])


def reverse_caches(apps, schema_editor):
    """Réversible : les colonnes disparaissent au reverse des AddField."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_partner_code_and_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedfile',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='api.channel'),
        ),
        migrations.AddField(
            model_name='receivedfile',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='api.partner'),
        ),
        migrations.RunPython(backfill_caches, reverse_caches),
    ]
