# Generated by Django 5.2.15 on 2026-06-19 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_receivedfile_partner_channel_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subfolder', models.CharField(blank=True, default='', max_length=255)),
                ('grammar', models.JSONField(blank=True, default=dict)),
                ('mandatory', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomenclatures', to='api.channel')),
                ('sub_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomenclatures', to='api.subtenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'subfolder'), name='uniq_nomenclature_channel_subfolder')],
            },
        ),
    ]
