# Generated by Django 5.2.15 on 2026-06-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_nomenclature'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cause_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='stage',
            field=models.CharField(choices=[('admission', 'Admission'), ('qualification', 'Qualification')], db_index=True, max_length=32),
        ),
    ]
