# Generated by Django 5.2.15 on 2026-06-19 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_filetriage_to_handled_drop_triageack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='username',
        ),
        migrations.AlterField(
            model_name='event',
            name='sub_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='api.subtenant'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='code',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='sub_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='api.subtenant'),
        ),
        migrations.AlterField(
            model_name='receivedfile',
            name='sub_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='api.subtenant'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(fields=('sub_tenant', 'code'), name='uniq_partner_subtenant_code'),
        ),
    ]
