# Generated by Django 5.2.15 on 2026-06-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_finalize_not_null_drop_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='stage',
            field=models.CharField(choices=[('admission', 'Admission'), ('qualification', 'Qualification'), ('triage', 'Triage (décision opérateur)')], db_index=True, max_length=32),
        ),
    ]
