# Generated by Django 5.2.15 on 2026-06-22 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_event_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='stage',
            field=models.CharField(choices=[('admission', 'Admission'), ('qualification', 'Qualification'), ('routing', 'Routage'), ('triage', 'Triage (décision opérateur)')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=128)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('data_type', models.CharField(blank=True, default='', max_length=64)),
                ('business_domain', models.CharField(blank=True, default='', max_length=64)),
                ('data_owner', models.CharField(blank=True, default='', max_length=128)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('layout_version', models.IntegerField(default=1)),
                ('target', models.JSONField(blank=True, default=dict)),
                ('strategy', models.CharField(blank=True, max_length=64, null=True)),
                ('strategy_params', models.JSONField(blank=True, default=dict)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='api.partner')),
                ('sub_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='api.subtenant')),
            ],
        ),
        migrations.AddField(
            model_name='receivedfile',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='api.route'),
        ),
        migrations.CreateModel(
            name='RoutePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.JSONField(blank=True, default=dict)),
                ('priority', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='api.route')),
                ('sub_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_patterns', to='api.subtenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('sub_tenant', 'code'), name='uniq_route_subtenant_code'),
        ),
    ]
