# Generated by Django 5.2.15 on 2026-06-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_seed_tee_routes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='route',
            name='uniq_route_subtenant_code',
        ),
        migrations.RemoveField(
            model_name='route',
            name='sub_tenant',
        ),
        migrations.RemoveField(
            model_name='routepattern',
            name='sub_tenant',
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('partner', 'code'), name='uniq_route_partner_code'),
        ),
    ]
