# Generated by Django 5.2.15 on 2026-06-22 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_routing_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routepattern',
            name='route',
        ),
        migrations.RemoveConstraint(
            model_name='nomenclature',
            name='uniq_nomenclature_channel_subfolder',
        ),
        migrations.RemoveConstraint(
            model_name='route',
            name='uniq_route_partner_code',
        ),
        migrations.RemoveField(
            model_name='route',
            name='partner',
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nomenclatures', to='api.route'),
        ),
        migrations.AddField(
            model_name='route',
            name='sub_tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='api.subtenant'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('sub_tenant', 'code'), name='uniq_route_subtenant_code'),
        ),
        migrations.DeleteModel(
            name='RoutePattern',
        ),
    ]
