# Generated by Django 5.2.15 on 2026-06-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_seed_tee_nomenclatures_routes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='route',
            name='uniq_route_subtenant_code',
        ),
        migrations.RemoveField(
            model_name='route',
            name='sub_tenant',
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('code',), name='uniq_route_code'),
        ),
    ]
