# Generated by Django 5.2.15 on 2026-06-22 12:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_route_uniq_route_subtenant_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='can_be_empty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='layout',
            field=models.JSONField(blank=True, default=dict, validators=[api.models.validate_layout]),
        ),
    ]
