# Generated by Django 5.2.15 on 2026-06-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_seed_tee_txt_nav_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='stage',
            field=models.CharField(choices=[('admission', 'Admission'), ('qualification', 'Qualification'), ('routing', 'Routage'), ('parsing', 'Parsing'), ('triage', 'Triage (décision opérateur)')], db_index=True, max_length=32),
        ),
    ]
