# Generated by Django 5.2.15 on 2026-06-23 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_nomenclature_to_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('sub_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_calendars', to='api.subtenant')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('is_open', models.BooleanField()),
                ('reason', models.CharField(max_length=255)),
                ('business_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='api.businesscalendar')),
                ('sub_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendar_exceptions', to='api.subtenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business_calendar', 'date'), name='uniq_calendar_exception_date')],
            },
        ),
        migrations.CreateModel(
            name='CalendarHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('label', models.CharField(max_length=255)),
                ('is_bank_holiday', models.BooleanField(default=False)),
                ('business_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='api.businesscalendar')),
                ('sub_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendar_holidays', to='api.subtenant')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('business_calendar', 'date'), name='uniq_calendar_date')],
            },
        ),
    ]
