# Generated by Django 5.2.15 on 2026-06-23 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_load_lu_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('absence_policy', models.CharField(choices=[('candidate', 'Candidate (onboarding)'), ('anomaly', 'Anomalie (erreur)')], default='candidate', help_text="entité absente du référentiel → candidate (onboarding, warning_action) ou anomaly (erreur). Appliquée uniformément par le moteur d'identification (§1.6-b).", max_length=16)),
                ('sub_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referentials', to='api.subtenant')),
            ],
        ),
        migrations.CreateModel(
            name='SubFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=16)),
                ('sub_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subfunds', to='api.subtenant')),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('sub_tenant', 'key'), name='uniq_subfund_key_per_tenant')],
            },
        ),
    ]
