# Generated by Django 5.2.15 on 2026-06-23 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_seed_subfund_referential'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(db_index=True, max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('sub_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identification_profiles', to='api.subtenant')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='identification_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='api.identificationprofile'),
        ),
        migrations.CreateModel(
            name='IdentificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('partition', 'Partition'), ('axis', 'Axe'), ('subordinate', 'Subordonné')], max_length=16)),
                ('required', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.identificationprofile')),
                ('referential', models.ForeignKey(blank=True, help_text='référentiel résolu pour ce champ. Null pour un axis (ex. date) qui ne résout aucun référentiel.', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.referential')),
                ('sub_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identification_rules', to='api.subtenant')),
            ],
            options={
                'ordering': ['profile', 'role', 'field'],
            },
        ),
        migrations.CreateModel(
            name='ReferentialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=16)),
                ('referential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='api.referential')),
                ('sub_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referential_entries', to='api.subtenant')),
            ],
            options={
                'ordering': ['referential', 'key'],
            },
        ),
        migrations.AddConstraint(
            model_name='identificationprofile',
            constraint=models.UniqueConstraint(fields=('sub_tenant', 'file_type'), name='uniq_profile_per_filetype'),
        ),
        migrations.AddConstraint(
            model_name='referentialentry',
            constraint=models.UniqueConstraint(fields=('sub_tenant', 'referential', 'key'), name='uniq_referential_entry'),
        ),
    ]
