# Generated by Django 5.2.15 on 2026-06-23 19:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_identification_descriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='run_id',
            field=models.CharField(blank=True, db_index=True, default=api.models._current_run_id, editable=False, max_length=32, null=True),
        ),
    ]
