# Generated by Django 5.2.15 on 2026-06-23 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_backfill_run_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubFundAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_code', models.CharField(db_index=True, max_length=255)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subfund_aliases', to='api.feed')),
                ('sub_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='api.subfund')),
                ('sub_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subfund_aliases', to='api.subtenant')),
            ],
            options={
                'ordering': ['feed', 'external_code'],
                'constraints': [models.UniqueConstraint(fields=('sub_tenant', 'feed', 'external_code'), name='uniq_subfund_alias')],
            },
        ),
    ]
