# Generated by Django 5.2.15 on 2026-06-23 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_subfundalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationPartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_fund_value', models.CharField(db_index=True, max_length=255)),
                ('valuation_date_value', models.CharField(db_index=True, max_length=64)),
                ('control_class', models.CharField(choices=[('blocking', 'Bloquant'), ('warning_action', 'Avertissement (action requise)'), ('warning_noaction', 'Avertissement (sans action)'), ('reject', 'Rejet (archivé, non retraité)'), ('recycle', 'Recyclage (retraitable)'), ('push', 'Confirmation (poussé)')], max_length=20)),
                ('is_known_subfund', models.BooleanField()),
                ('last_event_at', models.DateTimeField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identification_partitions', to='api.feed')),
                ('received_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identification_partitions', to='api.receivedfile')),
                ('sub_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identification_partitions', to='api.subfund')),
                ('sub_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identification_partitions', to='api.subtenant')),
            ],
            options={
                'ordering': ['-last_event_at'],
                'constraints': [models.UniqueConstraint(fields=('sub_tenant', 'feed', 'sub_fund_value', 'valuation_date_value'), name='uniq_identification_partition')],
            },
        ),
    ]
