# Generated by Django 5.2.15 on 2026-06-23 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_identificationpartition'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavCalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.CharField(choices=[('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('biweekly', 'Bimensuelle'), ('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle')], help_text="fréquence de calcul VNI, déclarative (pas d'expansion en dates ici).", max_length=16)),
                ('lag', models.PositiveSmallIntegerField(help_text='jours ouvrés entre la date de valo et la livraison attendue.')),
                ('deadline_time', models.TimeField(help_text='fuseau Europe/Luxembourg supposé ; le calcul effectif est différé (§3.8).')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=16)),
                ('business_calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_calendar_entries', to='api.businesscalendar')),
                ('sub_fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nav_calendar_entries', to='api.subfund')),
                ('sub_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nav_calendar_entries', to='api.subtenant')),
            ],
            options={
                'ordering': ['sub_fund'],
                'constraints': [models.UniqueConstraint(fields=('sub_tenant', 'sub_fund'), name='uniq_nav_calendar_entry')],
            },
        ),
    ]
